#ifndef GUARD_CONST_ANIMATION_H
#define GUARD_CONST_ANIMATION_H

enum {
    ANIM_NONE,
    ANIM_HOLDIT_LEFT,
    ANIM_OBJECTION_LEFT,
    ANIM_OBJECTION_RIGHT,
    ANIM_TAKETHAT_LEFT,
    // TODO: fill in
    ANIM_TESTIMONY_START = 34,
    ANIM_TESTIMONY_START_LEFT = 36,
    ANIM_TESTIMONY_START_RIGHT,
};

#endif//GUARD_CONST_ANIMATION_H
