#ifndef GUARD_CONST_ANIMATION_H
#define GUARD_CONST_ANIMATION_H

enum {
    ANIM_NONE,
    ANIM_HOLDIT_LEFT,
    ANIM_OBJECTION_LEFT,
    ANIM_OBJECTION_RIGHT,
    ANIM_TAKETHAT_LEFT,
    // TODO: fill in
};

#endif//GUARD_CONST_ANIMATION_H
